server:
  port: 8081

spring:
  datasource:
    # Cambiamos authdb por ecommerce_auth
    url: jdbc:postgresql://localhost:5432/ecommerce_auth
    username: postgres   
    password: JUAN123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true